# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)

get_event_type_display_names_from_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_event_type_display_names_from_events",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_wd.tasks import (
    add_event_category_display as add_event_category_display,
)

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

download_event_photos = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_wd.tasks",  # 🧪
    func_name="download_event_photos",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope.platform.tasks.analysis import dataframe_count as dataframe_count
from ecoscope.platform.tasks.config import set_bool_var as set_bool_var
from ecoscope.platform.tasks.config import (
    set_optional_string_var as set_optional_string_var,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import never as never
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)
from ecoscope_workflows_ext_wd.tasks import build_photo_records as build_photo_records
from ecoscope_workflows_ext_wd.tasks import (
    format_photo_records_table as format_photo_records_table,
)
from ecoscope_workflows_ext_wd.tasks import (
    generate_photo_records_report as generate_photo_records_report,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    events = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "serial_number",
                "event_type",
                "event_category",
                "title",
                "geometry",
                "event_details",
            ],
            include_details=True,
            include_null_geometry=True,
            include_display_values=False,
            include_updates=False,
            include_related_events=False,
            raise_on_empty=False,
            force_point_geometry=True,
            **(params.get("events") or {}),
        )
        .call()
    )

    events_local_time = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("events_local_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("events_local_time") or {}),
        )
        .call()
    )

    events_type_display = (
        task(get_event_type_display_names_from_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("events_type_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            events_gdf=events_local_time,
            append_category_names="never",
            **(params.get("events_type_display") or {}),
        )
        .call()
    )

    events_category_display = (
        task(add_event_category_display)
        .validate()
        .set_task_instance_id("events_category_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            df=events_type_display,
            **(params.get("events_category_display") or {}),
        )
        .call()
    )

    events_resolved = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("events_resolved")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_category_display,
            client=er_client,
            map_to_titles=True,
            ordered=True,
            **(params.get("events_resolved") or {}),
        )
        .call()
    )

    download_photos = (
        task(download_event_photos)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("download_photos")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            events=events_resolved,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            skip_download=False,
            attachments_subdir="attachments",
            **(params.get("download_photos") or {}),
        )
        .call()
    )

    report_language = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("report_language")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_language") or {}))
        .call()
    )

    report_title = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("report_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_title") or {}))
        .call()
    )

    organization = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("organization")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("organization") or {}))
        .call()
    )

    report_subtitle = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("report_subtitle")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_subtitle") or {}))
        .call()
    )

    intro_text = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("intro_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("intro_text") or {}))
        .call()
    )

    logo_path = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("logo_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("logo_path") or {}))
        .call()
    )

    oldest_first = (
        task(set_bool_var)
        .validate()
        .set_task_instance_id("oldest_first")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("oldest_first") or {}))
        .call()
    )

    include_details = (
        task(set_bool_var)
        .validate()
        .set_task_instance_id("include_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("include_details") or {}))
        .call()
    )

    norm_output_dir = (
        task(remove_file_scheme)
        .validate()
        .set_task_instance_id("norm_output_dir")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("norm_output_dir") or {}),
        )
        .call()
    )

    photo_records = (
        task(build_photo_records)
        .validate()
        .set_task_instance_id("photo_records")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            events=events_resolved,
            attachment_paths=download_photos,
            output_dir=norm_output_dir,
            sort_ascending=oldest_first,
            language=report_language,
            **(params.get("photo_records") or {}),
        )
        .call()
    )

    persist_photo_records = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_photo_records")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=photo_records,
            filetype="csv",
            filename="photo_records",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("persist_photo_records") or {}),
        )
        .call()
    )

    photo_records_report = (
        task(generate_photo_records_report)
        .validate()
        .set_task_instance_id("photo_records_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            records=photo_records,
            output_dir=norm_output_dir,
            time_range=time_range,
            language=report_language,
            title=report_title,
            organization=organization,
            subtitle=report_subtitle,
            intro_text=intro_text,
            logo_path=logo_path,
            include_details=include_details,
            **(params.get("photo_records_report") or {}),
        )
        .call()
    )

    total_photos = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("total_photos")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(df=photo_records, **(params.get("total_photos") or {}))
        .call()
    )

    total_photos_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_photos_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Photos",
            data=total_photos,
            decimal_places=0,
            **(params.get("total_photos_widget") or {}),
        )
        .call()
    )

    total_events = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("total_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=photo_records,
            column_name="event_id",
            **(params.get("total_events") or {}),
        )
        .call()
    )

    total_events_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_events_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Events with Photos",
            data=total_events,
            decimal_places=0,
            **(params.get("total_events_widget") or {}),
        )
        .call()
    )

    photo_records_html = (
        task(format_photo_records_table)
        .validate()
        .set_task_instance_id("photo_records_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            records=photo_records,
            language=report_language,
            include_details=include_details,
            thumbnail_size=480,
            **(params.get("photo_records_html") or {}),
        )
        .call()
    )

    persist_photo_records_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_photo_records_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            text=photo_records_html,
            filename="photo_records_table.html",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("persist_photo_records_html") or {}),
        )
        .call()
    )

    photo_records_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("photo_records_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Photographic Records",
            data=persist_photo_records_html,
            **(params.get("photo_records_widget") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[total_photos_widget, total_events_widget, photo_records_widget],
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
