# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope.platform.tasks.analysis import dataframe_count as dataframe_count
from ecoscope.platform.tasks.config import set_bool_var as set_bool_var
from ecoscope.platform.tasks.config import (
    set_optional_string_var as set_optional_string_var,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    get_event_type_display_names_from_events as get_event_type_display_names_from_events,
)
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import process_events_details as process_events_details
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import (
    create_files_single_view as create_files_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)
from ecoscope_workflows_ext_wd.tasks import (
    add_event_category_display as add_event_category_display,
)
from ecoscope_workflows_ext_wd.tasks import build_photo_records as build_photo_records
from ecoscope_workflows_ext_wd.tasks import (
    download_event_photos as download_event_photos,
)
from ecoscope_workflows_ext_wd.tasks import (
    format_photo_records_table as format_photo_records_table,
)
from ecoscope_workflows_ext_wd.tasks import (
    generate_photo_records_report as generate_photo_records_report,
)
from ecoscope_workflows_ext_wd.tasks import (
    renumber_photo_records as renumber_photo_records,
)
from ecoscope_workflows_ext_wd.tasks import set_int_var as set_int_var
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    events = (
        task(get_events)
        .validate()
        .set_task_instance_id("events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "serial_number",
                "event_type",
                "event_category",
                "title",
                "geometry",
                "event_details",
            ],
            include_details=True,
            include_null_geometry=True,
            include_display_values=False,
            include_updates=False,
            include_related_events=False,
            raise_on_empty=False,
            force_point_geometry=True,
            **(params.get("events") or {}),
        )
        .call()
    )

    events_local_time = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("events_local_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("events_local_time") or {}),
        )
        .call()
    )

    events_type_display = (
        task(get_event_type_display_names_from_events)
        .validate()
        .set_task_instance_id("events_type_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            events_gdf=events_local_time,
            append_category_names="never",
            **(params.get("events_type_display") or {}),
        )
        .call()
    )

    events_category_display = (
        task(add_event_category_display)
        .validate()
        .set_task_instance_id("events_category_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            df=events_type_display,
            **(params.get("events_category_display") or {}),
        )
        .call()
    )

    events_resolved = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("events_resolved")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_category_display,
            client=er_client,
            map_to_titles=True,
            ordered=True,
            **(params.get("events_resolved") or {}),
        )
        .call()
    )

    download_photos = (
        task(download_event_photos)
        .validate()
        .set_task_instance_id("download_photos")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            events=events_resolved,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            skip_download=False,
            attachments_subdir="attachments",
            **(params.get("download_photos") or {}),
        )
        .call()
    )

    thumbnail_size = (
        task(set_int_var)
        .validate()
        .set_task_instance_id("thumbnail_size")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("thumbnail_size") or {}))
        .call()
    )

    report_language = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("report_language")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_language") or {}))
        .call()
    )

    report_title = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("report_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_title") or {}))
        .call()
    )

    organization = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("organization")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("organization") or {}))
        .call()
    )

    report_subtitle = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("report_subtitle")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_subtitle") or {}))
        .call()
    )

    intro_text = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("intro_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("intro_text") or {}))
        .call()
    )

    logo_path = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("logo_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("logo_path") or {}))
        .call()
    )

    oldest_first = (
        task(set_bool_var)
        .validate()
        .set_task_instance_id("oldest_first")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("oldest_first") or {}))
        .call()
    )

    include_details = (
        task(set_bool_var)
        .validate()
        .set_task_instance_id("include_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("include_details") or {}))
        .call()
    )

    norm_output_dir = (
        task(remove_file_scheme)
        .validate()
        .set_task_instance_id("norm_output_dir")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("norm_output_dir") or {}),
        )
        .call()
    )

    photo_records = (
        task(build_photo_records)
        .validate()
        .set_task_instance_id("photo_records")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            events=events_resolved,
            attachment_paths=download_photos,
            output_dir=norm_output_dir,
            sort_ascending=oldest_first,
            language=report_language,
            **(params.get("photo_records") or {}),
        )
        .call()
    )

    persist_photo_records = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_photo_records")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=photo_records,
            filetype="csv",
            filename="photo_records",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("persist_photo_records") or {}),
        )
        .call()
    )

    records_indexed = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("records_indexed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=photo_records,
            time_col="time",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("records_indexed") or {}),
        )
        .call()
    )

    records_split = (
        task(split_groups)
        .validate()
        .set_task_instance_id("records_split")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=records_indexed, groupers=groupers, **(params.get("records_split") or {})
        )
        .call()
    )

    records_by_view = (
        task(renumber_photo_records)
        .validate()
        .set_task_instance_id("records_by_view")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("records_by_view") or {}))
        .mapvalues(argnames=["records"], argvalues=records_split)
    )

    photo_records_report = (
        task(generate_photo_records_report)
        .validate()
        .set_task_instance_id("photo_records_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=norm_output_dir,
            time_range=time_range,
            language=report_language,
            title=report_title,
            organization=organization,
            subtitle=report_subtitle,
            intro_text=intro_text,
            logo_path=logo_path,
            include_details=include_details,
            **(params.get("photo_records_report") or {}),
        )
        .map(argnames=["composite_filter", "records"], argvalues=records_by_view)
    )

    total_photos = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("total_photos")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("total_photos") or {}))
        .mapvalues(argnames=["df"], argvalues=records_by_view)
    )

    total_photos_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_photos_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Photos",
            decimal_places=0,
            **(params.get("total_photos_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_photos)
    )

    total_photos_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("total_photos_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_photos_widget, **(params.get("total_photos_merged") or {})
        )
        .call()
    )

    total_events = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("total_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(column_name="event_id", **(params.get("total_events") or {}))
        .mapvalues(argnames=["df"], argvalues=records_by_view)
    )

    total_events_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_events_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Events with Photos",
            decimal_places=0,
            **(params.get("total_events_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_events)
    )

    total_events_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("total_events_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_events_widget, **(params.get("total_events_merged") or {})
        )
        .call()
    )

    photo_records_html = (
        task(format_photo_records_table)
        .validate()
        .set_task_instance_id("photo_records_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            language=report_language,
            include_details=include_details,
            thumbnail_size=thumbnail_size,
            **(params.get("photo_records_html") or {}),
        )
        .mapvalues(argnames=["records"], argvalues=records_by_view)
    )

    persist_photo_records_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_photo_records_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("persist_photo_records_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=photo_records_html)
    )

    photo_records_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("photo_records_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Photographic Records", **(params.get("photo_records_widget") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_photo_records_html)
    )

    photo_records_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("photo_records_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=photo_records_widget, **(params.get("photo_records_merged") or {})
        )
        .call()
    )

    report_file_views = (
        task(create_files_single_view)
        .validate()
        .set_task_instance_id("report_file_views")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_file_views") or {}))
        .map(argnames=["view", "files"], argvalues=photo_records_report)
    )

    csv_file_view = (
        task(create_files_single_view)
        .validate()
        .set_task_instance_id("csv_file_view")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(files=persist_photo_records, **(params.get("csv_file_view") or {}))
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[total_photos_merged, total_events_merged, photo_records_merged],
            groupers=groupers,
            time_range=time_range,
            files=[report_file_views, csv_file_view],
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
